package ai

import (
	"context"
	"fmt"
	"strings"
)

// MockClient is a deterministic Client for tests and the audit pipeline's
// mocked-AI mode. Identical input always produces identical output — that's
// the determinism rule the pipeline tests rely on.
type MockClient struct {
	// FixOverrides keys by IssueID to override the default rewrite, so a test
	// can pin a specific suggestion without changing the source it derives from.
	FixOverrides map[string]string
}

func NewMockClient() *MockClient {
	return &MockClient{FixOverrides: map[string]string{}}
}

func (m *MockClient) GenerateFix(_ context.Context, req FixRequest) (FixResponse, error) {
	return FixResponse{
		IssueID:   req.IssueID,
		Suggested: m.suggestionFor(req),
		Reasoning: fmt.Sprintf("Generated by mock for check=%s severity=%s", req.CheckID, req.Severity),
		TokensIn:  150,
		TokensOut: 60,
		ModelUsed: "mock-1.0",
	}, nil
}

func (m *MockClient) GenerateFixBatch(_ context.Context, req BatchFixRequest) ([]FixResponse, error) {
	if len(req.Issues) > 10 {
		return nil, ErrBatchTooLarge
	}
	out := make([]FixResponse, len(req.Issues))
	for i, iss := range req.Issues {
		out[i] = FixResponse{
			IssueID:   iss.IssueID,
			Suggested: m.suggestionFor(iss),
			TokensIn:  120,
			TokensOut: 50,
			ModelUsed: "mock-1.0",
		}
	}
	return out, nil
}

func (m *MockClient) GenerateSummary(_ context.Context, req SummaryRequest) (SummaryResponse, error) {
	verdict := summaryVerdict(req)
	steps := []string{
		"Fix the critical issues first — they're blocking GMC approval.",
		"Audit policy pages: shipping, terms, privacy, refund.",
		"Refresh thin product descriptions and ALL-CAPS titles.",
		"Re-run the audit after changes to confirm.",
	}
	if req.IssueCounts["critical"] == 0 && req.IssueCounts["error"] == 0 {
		steps = []string{
			"No blocking issues — submit the feed to GMC.",
			"Watch the warning-tier items in the next monthly audit.",
		}
	}
	return SummaryResponse{
		Summary:   verdict,
		NextSteps: steps,
		TokensIn:  300,
		TokensOut: 120,
		ModelUsed: "mock-1.0",
	}, nil
}

// suggestionFor derives a deterministic rewrite based on the issue's CheckID
// and Detail so the same input always yields the same output.
func (m *MockClient) suggestionFor(req FixRequest) string {
	if v, ok := m.FixOverrides[req.IssueID]; ok {
		return v
	}
	switch req.CheckID {
	case "product_schema_complete":
		return "Add the missing schema fields (name, image, description, brand, offers.price/priceCurrency/availability) so GMC can match the product."
	case "product_schema_present":
		return `Wrap the product with a JSON-LD <script type="application/ld+json"> block emitting Product, Offer, and Brand.`
	case "product_identifier_present":
		return "Set the Barcode field on the variant to the manufacturer's GTIN, or set the google.identifier_exists metafield to false."
	case "product_title_quality":
		return "Rewrite the title in title case, drop the exclamation marks, and keep it under 70 characters."
	case "product_description_quality":
		return "Replace the placeholder copy with a 2–3 sentence description covering material, dimensions, and the buyer benefit."
	case "image_alt_quality":
		return fmt.Sprintf("Set alt to a short description of what the image shows for %q.",
			coalesce(req.ProductTitle, "this product"))
	case "canonical_tags_present":
		return `Add <link rel="canonical" href="{{ canonical_url }}"> to layout/theme.liquid.`
	case "shipping_policy_linked", "refund_policy_linked":
		return "Link the policy from the footer menu so it's reachable in one click from every page."
	case "currency_consistency":
		return "Switch this product's priceCurrency to match the rest of the catalog (most products are USD)."
	case "broken_product_links":
		return "Add a 301 redirect from the missing URL to the closest replacement product or its collection."
	}
	return fmt.Sprintf("Apply the steps under the \"How to apply\" panel for %s.", req.CheckID)
}

func summaryVerdict(req SummaryRequest) string {
	switch {
	case req.IssueCounts["critical"] > 0:
		return fmt.Sprintf("This store has %d critical and %d error-tier issues that will block GMC approval — address them before launching ads.",
			req.IssueCounts["critical"], req.IssueCounts["error"])
	case req.IssueCounts["error"] > 0:
		return fmt.Sprintf("This store is close to GMC-ready (score %d/100); fix the %d remaining error-tier items before submitting the feed.",
			req.Score, req.IssueCounts["error"])
	case req.IssueCounts["warning"] > 0:
		return fmt.Sprintf("This store passes GMC's hard checks (score %d/100); the %d warnings are quality polish, not blockers.",
			req.Score, req.IssueCounts["warning"])
	default:
		return fmt.Sprintf("This store is GMC-ready — score %d/100 with no blocking issues.", req.Score)
	}
}

// ----------------------------------------------------------------------------
// In-memory settings provider for tests.
// ----------------------------------------------------------------------------

type StaticSettings struct {
	BaseURL string
	APIKey  string
	Model   string
}

func (s StaticSettings) Get(_ context.Context, key string) (string, error) {
	switch key {
	case SettingBaseURL:
		return s.BaseURL, nil
	case SettingAPIKey:
		return s.APIKey, nil
	case SettingModel:
		return s.Model, nil
	}
	return "", fmt.Errorf("unknown setting %q", key)
}

// quoteIDs is a tiny helper used by the mock's prompt batch parsing in tests.
// Kept here so tests can import it without poking at unexported helpers.
func quoteIDs(ids []string) string { return strings.Join(ids, ", ") }
